version: "3.3"

services:
  traefik:
    image: traefik:v2.6
    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmmode
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --pilot.token=4f869d98-2658-48e6-9405-c97c9183d932
      - --certificatesresolvers.http.acme.email=${EMAIL:-bresnow@xdesk.app}
      - --certificatesresolvers.http.acme.storage=/certificates/acme.json
      - --certificatesresolvers.http.acme.tlschallenge=true
      - --accesslog
      - --log
      - --api
      - --api.dashboard
      - --api.insecure
    ports:
      - 80:80
      - 443:443
    deploy:
      placement:
        constraints:
          - node.labels.traefik-public.traefik-public-certificates == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.middlewares.admin-auth.basicauth.users=${BASIC_AUTH:-bresnow:$$2y$$05$$SaGrMs06FYtov8OQe8pcve6EEvhkSpd0rscFkDrZiHqgfnJPlCGJi}
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.traefik-public-http.rule=Host(`${TRAEFIK_HOST:-proxy.fltngmmth.com}`)
        - traefik.http.routers.traefik-public-http.entrypoints=http
        - traefik.http.routers.traefik-public-http.middlewares=https-redirect
        - traefik.http.routers.traefik-public-https.rule=Host(`${TRAEFIK_HOST:-proxy.fltngmmth.com}`)
        - traefik.http.routers.traefik-public-https.entrypoints=https
        - traefik.http.routers.traefik-public-https.tls=true
        - traefik.http.routers.traefik-public-https.service=api@internal
        - traefik.http.routers.traefik-public-https.tls.certresolver=http
        - traefik.http.services.traefik-public.loadbalancer.server.port=8080

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certs:/certificates

    networks:
      - traefik-public
volumes:
  traefik-certs:
  # peer1:

networks:
  traefik-public:
    external: true
