name: Build Latest
on:
  push:
    branches:
      - main

jobs:
  install_deps:
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - name: Dependencies Script
        uses: bresnow/remix.gun/.github/workflows/node-dependencies.yml@main
  build_latest:
    needs: install_deps
    if: ${{ success() }}
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - name: zsh exec
        run: zsh
      - name: Node Dependencies
        run: |
          yarn
          yarn add global ts-node
          yarn add global zx
      - uses: actions/checkout@v3
      - name: Build and Push As Latest
        run: ts-node-esm scripts/docker/swarm/build-push-latest.ts
