name: Build Latest
on:
  push:
    branches:
      - main

jobs:
  install_deps:
    uses: bresnow/remix.gun/.github/workflows/node-dependencies.yml@main
  build_latest:
    needs: install_deps
    if: ${{ success() }}
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push As Latest
        run: |
          npx zx scripts/esm/docker/build-push-dh.mjs -L
          npx zx scripts/esm/docker/build-push-dh.mjs -L -G
          npx zx scripts/esm/docker/build-push-dh.mjs
          npx zx scripts/esm/docker/build-push-dh.mjs -G
