name: Build Latest Docker Image and Push to Registries
on:
  workflow_call:

jobs:
  build_latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17
      - run: npm install
      - run: npx zx scripts/esm/docker/build-push-dh.mjs -L
      - run: npx zx scripts/esm/docker/build-push-dh.mjs -L -G
      - run: npx zx scripts/esm/docker/build-push-dh.mjs
      - run: npx zx scripts/esm/docker/build-push-dh.mjs -G
