name: Build Latest Docker Image and Push to Registries
on:
  workflow_call:

jobs:
  docker_hub:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DH_ACCESS_TOKEN }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17
      - run: npm install --force
      - run: npx zx scripts/esm/docker/build-push-dh.mjs -L
      - run: npx zx scripts/esm/docker/build-push-dh.mjs
  ghcr_io:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_ACCESS_TOKEN }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17
      - run: npm install --force
      - run: npx zx scripts/esm/docker/build-push-dh.mjs -L -G
      - run: npx zx scripts/esm/docker/build-push-dh.mjs -G
