name: Build Latest
on:
  workflow_call:

jobs:
  # install_deps:
  #   uses: bresnow/remix.gun/.github/workflows/node-dependencies.yml@main
  build_latest:
    # needs: install_deps
    # if: ${{ success() }}
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push As Latest
        run: |
          yarn
          yarn zx scripts/esm/docker/build-push-dh.mjs -L
          yarn zx scripts/esm/docker/build-push-dh.mjs -L -G
          yarn zx scripts/esm/docker/build-push-dh.mjs
          yarn zx scripts/esm/docker/build-push-dh.mjs -G
