name: Build Latest
on:
  workflow_call:

jobs:
  build_latest:
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push As Latest
        run: |
          yarn
          npx zx scripts/esm/docker/build-push-dh.mjs -L
          npx zx scripts/esm/docker/build-push-dh.mjs -L -G
          npx zx scripts/esm/docker/build-push-dh.mjs
          npx zx scripts/esm/docker/build-push-dh.mjs -G
