name: Build Latest
on:
  push:
    branches:
      - main

jobs:
  install_deps:
    uses: bresnow/remix.gun/.github/workflows/node-dependencies.yml@main
  build_latest:
    needs: install_deps
    if: ${{ success() }}
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push As Latest
        run: |
          npm run ts-node-esm scripts/docker/build-push-dh.ts -L
          npm run ts-node-esm scripts/docker/build-push-dh.ts -L -G
          npm run ts-node-esm scripts/docker/build-push-dh.ts
          npm run ts-node-esm scripts/docker/build-push-dh.ts -G
