name: Build Latest
on:
  push:
    branches:
      - main
jobs:
  build_latest:
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build and Push As Latest
        run: npx zx scripts/docker/swarm/build-push-latest.mjs
