name: Docker Cleanup
on:
  workflow_dispatch:

jobs:
  stack_deploy:
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v2
      - name: zsh exec
        run: zsh
      - name: yarn install
        run: yarn
      - name: Cleanup
        run: |
          docker image prune --force
          docker volume prune --force
          docker container prune --force
