name: Docker Cleanup
on:
  workflow_call:
## Cleanup dangling artifacts to save server space
jobs:
  cleanup:
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v2
      - name: Cleanup
        run: |
          docker image prune --force
          docker volume prune --force
          docker container prune --force
