name: Deploy Remix.Gun App
on:
  workflow_dispatch:
    inputs:
      keypair:
        description: SEA pair for app authentication
        required: true
        type: string
      domain:
        description: App host name
        required: true
        type: string
      port:
        description: App port
        required: true
        type: string
      relay-peer:
        description: Relay peers (separated by comma)
        required: true
        type: string
      service-name:
        description: Service name in docker
        required: true
        type: string

jobs:
  traefik_deploy:
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - name: Deploy App
        run: |
          yarn
          npx zx scripts/esm/docker/swarm/deploy-app.mjs --keypair ${{ inputs.keypair }} --domain ${{ inputs.domain }} --port ${{ inputs.port }} --relay-peer ${{ inputs.relay-peer }} ${{ inputs.service-name }}
