name: Deploy Stack
on:
  workflow_dispatch:
jobs:
  stack_deploy:
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - name: Deploy App With Traefik
        run: npx zx scripts/esm/docker/swarm/traefik-service.ts
      - name: Cleanup
        run: |
          docker image prune --force
          docker volume prune --force
          docker container prune --force
      - name: Logs
        run: npx zx scripts/esm/docker/swarm/service-log.ts
