name: Deploy Stack
on:
  workflow_dispatch:

jobs:
  stack_deploy:
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v2
      - name: zsh exec
        run: |
          zsh
      - name: Deploy App With Traefik
        run: npx zx scripts/docker/swarm/traefik-service.mjs
