name: Deploy Remix.Gun App
on:
  workflow_dispatch:
    inputs:
      keypair:
        description: SEA pair for app authentication
        required: true
        type: string
      domain:
        description: App host name
        required: true
        type: string
      port:
        description: App port
        required: true
        type: string
      relay-peer:
        description: Relay peers (separated by comma)
        required: true
        type: string
      service-name:
        description: Service name in docker
        required: true
        type: string

jobs:
  deploy:
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - name: Deploy App
        env:
          SEA_PAIR: ${{ fromJson(${{ inputs.keypair }}) }}
          DOMAIN: ${{ inputs.domain }}
          PORT: ${{ inputs.port }}
          RELAY_PEER: ${{ inputs.relay-peer }}
          SERVICE_NAME: ${{ inputs.service-name }}
        run: |
          echo ${{ env.SEA_PAIR }}
          echo $SEA_PAIR
