name: DEPLOY ON MAIN SERVER
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version Number
        required: true
      stack_name:
        type: string
        description: Stack Name
        required: true
      image:
        type: choice
        description: Image
        required: true
        options:
          - "bresnow/rmx-gun"
          - "bresnow/cnxt"
      traefik_deploy:
        type: boolean
        description: Deploy Traefik Service?
        required: true

env:
  STACK_NAME: ${{ github.event.inputs.stack_name }}
  IMAGE: ${{ github.event.inputs.image }}
  VERSION: ${{ github.event.inputs.version }}
jobs:
  swarm_deploy:
    runs-on: [self-hosted, linux, main-server]
    steps:
