name: TSV to Encrypted Radix
on:
  workflow_dispatch:
    branches:
      - cnxt
    inputs:
      tsv-path:
        description: Path To TSV File
        required: true
        type: string
      relay-peer:
        description: Relay peers (separated by comma)
        required: false
        type: string
# App authentication only works iff SEA Keypair is destructured. Best to use repository secrets
jobs:
  tsv_rad:
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - name: Run
        env:
          TSV_PATH: ${{ inputs.tsv-path }}
          PEERS: ${{ inputs.relay-peer }}
          PUB: ${{ secrets.PUB }}
          PRIV: ${{ secrets.PRIV }}
          EPUB: ${{ secrets.EPUB }}
          EPRIV: ${{ secrets.EPRIV }}
        run: |
          yarn
          node scripts/esm/tsv/email-dist.mjs
