name: Docker Service Log
on:
  workflow_call:

jobs:
  stack_deploy:
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v2
      - name: Logs
        run: ts-node --esm scripts/docker/swarm/service-log.ts
