name: Docker Service Log
on:
  workflow_call:
  workflow_dispatch:

jobs:
  stack_deploy:
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v2
      - name: Logs
        run: |
          docker service logs remix-gun_traefik
          docker service logs remix-gun_fltngmmth
          docker service logs remix-gun_cnxt
