name: Docker Service Log
on:
  workflow_call:
  workflow_dispatch:
# RUNS LOGS FOR ALL SERVICES
jobs:
  service_logs:
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: Node Dependencies
        run: |
          yarn 
          npx zx scripts/esm/docker/swarm/service-log.mjs
