name: Docker Service Log
on:
  workflow_call:
  workflow_dispatch:

jobs:
  stack_deploy:
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v2
      - name: Logs
        run: |
          yarn
          npx zx scripts/esm/docker/swarm/service-log.mjs
