name: Docker Service Log
on:
  workflow_dispatch:
  workflow_call:

jobs:
  stack_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 17.x]
    steps:
      - uses: actions/checkout@v2
      - name: zsh exec
        run: zsh
      - name: Logs
        run: npx zx scripts/docker/swarm/service-log.mjs
