# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Check for exisiting directory
        run: "(test -d ~/FLTNGMMTH && rm -rf ~/FLTNGMMTH) || echo app does not exist, skipping step"

      - name: Clone Repository
        run: |
          git clone git@github.com:bresnow/remix-gun-db_starter.git ~/FLTNGMMTH
          cd ~/FLTNGMMTH

      - name: Build Docker Image & Push to Github Registry
        env:
          VERSION: latest

        run: |
          docker build -t bresnow/fltngmmth_dev:${{ env.VERSION }} .
          docker push bresnow/fltngmmth_dev:${{ env.VERSION }}

      - name: Deploy Docker Swarm Script
        run: |
          export APP_KEY_PAIR=${{secrets.APP_KEY_PAIR}}
          docker stack rm fltngmmth_dev
          docker stack deploy -c docker_stack.yml fltngmmth_dev

      - name: Clean Up
        run: |
          rm -rf ~/FLTNGMMTH
          docker image prune 
          docker volume prune
