name: Traefik Service Prep
on:
  workflow_dispatch:
  workflow_call:
##  - RUN ONLY ONCE IN PREP FOR TRAEFIK SERVICE DEPLOYMENT
## Makes sure that the volume containing SSL certificates and the traefik service stay on the same node
## No matter how many nodes are added to the swarm cluster
jobs:
  prep_swarm:
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v2
      - name: Deploy App With Traefik
        run: |
          yarn
          npx zx scripts/esm/docker/swarm/prep.mjs
