name: Traefik Service Prep
on:
  workflow_dispatch:
  workflow_call:

jobs:
  stack_deploy:
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v2
      - name: zsh exec
        run: zsh
      - name: yarn install
        run: yarn
      - name: Deploy App With Traefik
        run: npx zx scripts/docker/swarm/prep.mjs
