name: Traefik Service Prep
on:
  workflow_dispatch:
  workflow_call:

jobs:
  install_deps:
    uses: bresnow/remix.gun/.github/workflows/node-dependencies.yml@main
  stack_deploy:
    needs: install_deps
    if: ${{ success() }}
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v2
      - name: Deploy App With Traefik
        run: npx zx scripts/esm/docker/swarm/prep.ts
