name: Traefik Service Prep
on:
  workflow_dispatch:
  workflow_call:

jobs:
  prep_swarm:
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v2
      - name: Deploy App With Traefik
        run: |
          yarn
          npx zx scripts/esm/docker/swarm/prep.mjs
