name: Dependency Install
on:
  workflow_call:

jobs:
  build_latest:
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - name: Node Dependencies
        run: |
          nvm install 17
          nvm use 17
          yarn install
          yarn add global zx
          yarn add global typescript
