name: Yarn
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Node Setup
      - uses: actions/setup-node@v3
        with:
          node-version: 17
      - run: yarn
      - uses: actions/checkout@v3
      - name: Build and Push Version & Latest
        run: yarn build
