name: Update Demo Services
## Demo apps update to latest version (without using "latest" version tag) Bleeding edge baby!
on:
  push:
    branches:
      - main

jobs:
  npm_build:
    uses: bresnow/remix.gun/.github/workflows/node-build.yml@main
  push_image:
    uses: bresnow/remix.gun/.github/workflows/build-latest.yml@main
  update_apps:
    ## Matrix strategy essentially running a forEach method
    strategy:
      matrix:
        service-name: [demo, app, cnxt]
        include:
          - service-name: demo
            domain: remix-gun.fltngmmth.com
            stack-name: remix-gun
          - service-name: cnxt
            domain: dev.cnxt.app
            stack-name: cnxt-app
          - service-name: app
            domain: peer.fltngmmth.com
            stack-name: remix-peer
    needs: [yarn_build, push_image]
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - name: Export Environment and Deploy Updates
        run: |
          yarn
          export VERSION="$(npx zx scripts/esm/pkg-utils.mjs -v)"
          export SERVICE_NAME=${{ matrix.service-name }}
          export DOMAIN=${{ matrix.domain }}
          export PUB=${{ secrets.PUB }}
          export PRIV=${{ secrets.PRIV }}
          export EPUB=${{ secrets.EPUB }}
          export EPRIV=${{ secrets.EPRIV }}
          docker stack deploy -c swarm-stacks/demo.yml ${{ matrix.stack-name }}
  cleanup:
    needs: update_apps
    uses: bresnow/remix.gun/.github/workflows/cleanup.yml@main
  logs:
    needs: update_apps
    uses: bresnow/remix.gun/.github/workflows/log.yml@main
