name: Update App Services
on:
  push:
    branches:
      - main

jobs:
  install_deps:
    uses: bresnow/remix.gun/.github/workflows/node-dependencies.yml@main
  push_docker:
    uses: bresnow/remix.gun/.github/workflows/build-latest.yml@main
  docker:
    needs: [install_deps, push_docker]
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: Update Swarm Stack
        run: |
          yarn
          npx zx scripts/esm/docker/deploy-stack.mjs

  cleanup:
    needs: docker
    uses: bresnow/remix.gun/.github/workflows/cleanup.yml@main
  logs:
    needs: docker
    uses: bresnow/remix.gun/.github/workflows/log.yml@main
