name: Update Demo Services
## Demo apps update to latest version (without using "latest" version tag) Bleeding edge baby!
on:
  push:
    branches:
      - cnxt

jobs:
  yarn_build:
    uses: bresnow/remix.gun/.github/workflows/node-build.yml@cnxt
  push_image:
    uses: bresnow/remix.gun/.github/workflows/build-latest.yml@cnxt
  update_apps:
    ## Matrix strategy essentially running a forEach method
    strategy:
      matrix:
        service-name: [cnxt]
        include:
          - service-name: cnxt
            domain: dev.cnxt.app
            stack-name: cnxt-app
    needs: [yarn_build, push_image]
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - name: Export Environment and Deploy Updates
        env:
          SERVICE_NAME: ${{ matrix.service-name }}
          DOMAIN: ${{ matrix.domain }}
          PUB: ${{ secrets.PUB }}
          PRIV: ${{ secrets.PRIV }}
          EPUB: ${{ secrets.EPUB }}
          EPRIV: ${{ secrets.EPRIV }}
          IMAGE: cnxt
        run: |
          yarn
          docker stack deploy -c swarm-stacks/demo.yml ${{ matrix.stack-name }}
  cleanup:
    needs: update_apps
    uses: bresnow/remix.gun/.github/workflows/cleanup.yml@cnxt
  logs:
    needs: update_apps
    uses: bresnow/remix.gun/.github/workflows/log.yml@cnxt
