name: Update App Services
on:
  push:
    branches:
      - main

jobs:
  yarn_build:
    uses: bresnow/remix.gun/.github/workflows/node-dependencies.yml@main
  build_push_image:
    uses: bresnow/remix.gun/.github/workflows/build-latest.yml@main
  deploy-stack_traefik:
    needs: [yarn_build, build_push_image]
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: Update Swarm Stack
        run: |
          yarn
          npx zx scripts/esm/docker/deploy-stack.mjs

  cleanup:
    needs: deploy-stack_traefik
    uses: bresnow/remix.gun/.github/workflows/cleanup.yml@main
  logs:
    needs: deploy-stack_traefik
    uses: bresnow/remix.gun/.github/workflows/log.yml@main
