name: Update App Services
on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - name: zsh exec
        run: zsh
      - name: yarn install
        run: yarn
      - uses: actions/checkout@v3
      - name: Name and Version From package.json
        id: package_version
        run: echo "::set-output name=package::$( yarn ts-node-esm scripts/pkg-utils.ts )"
      - name: Update Swarm Stack
        run: |
          export VERSION=${{ fromJson(steps.package_version.output.package).version }}
          docker stack deploy -c swarm-stacks/remix-gun.yml ${{fromJson(steps.package_version.output.package).name }}
      - name: Clean Up
        run: |
          docker image prune --force
          docker volume prune --force
          docker container prune --force
      - name: Logs
        run: yarn ts-node-esm scripts/docker/swarm/service-log.ts
