name: Update App Services
on:
  push:
    branches:
      - main

jobs:
  install_deps:
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - name: Dependencies Script
        uses: ./.github/workflows/node-dependencies.yml
  pkg_props:
    needs: install_deps
    if: ${{ success() }}
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - name: Name and Version From package.json
        id: pkg
        run: echo "::set-output name=package::$( ts-node-esm scripts/pkg-utils.ts )"
  docker:
    needs: pkg_props
    if: ${{ fromJson(steps.package_version.output.package) != null }}
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - name: Update Swarm Stack
        run: |
          echo ${{ fromJson(steps.package_version.output.package) }} 
          export VERSION=${{ fromJson(steps.package_version.output.package).version }}
          docker stack deploy -c swarm-stacks/remix-gun.yml ${{fromJson(steps.package_version.output.package).name }}
  cleanup:
    needs: docker
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - name: Dependencies Script
        uses: ./.github/workflows/cleanup.yml
