name: Update App Services
on:
  push:
    branches:
      - main

jobs:
  install_deps:
    uses: bresnow/remix.gun/.github/workflows/node-dependencies.yml@main
  pkg_props:
    needs: install_deps
    if: ${{ success() }}
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - name: Name and Version From package.json
        id: pkg
        run: echo "::set-output name=package::$( npm run ts-node-esm scripts/pkg-utils.ts )"
  docker:
    runs-on:
      - self-hosted
      - main-server
    steps:
      - uses: actions/checkout@v3
      - name: Name and Version From package.json
        id: pkg
        run: echo "::set-output name=package::$( npm run ts-node-esm scripts/pkg-utils.ts )"
      - uses: actions/checkout@v3
      - name: Update Swarm Stack
        run: |
          echo ${{ fromJson(steps.pkg.output.package) }} 
          export VERSION=${{ fromJson(steps.pkg.output.package).version }}
          docker stack deploy -c swarm-stacks/remix-gun.yml ${{fromJson(steps.pkg.output.package).name }}
  cleanup:
    needs: docker
    uses: bresnow/remix.gun/.github/workflows/cleanup.yml@main
  logs:
    needs: docker
    uses: bresnow/remix.gun/.github/workflows/log.yml@main
